# Generated by Django 5.1.7 on 2025-04-04 09:46

import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='business_n2ame')),
                ('inn_number', models.CharField(max_length=12)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_description', models.TextField()),
                ('business_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=127)),
                ('bic_bank_number', models.CharField(max_length=9)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_routing_number', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
